image: openjdk:8

build:
  stage: build
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make

front_end_test: 
  stage: test
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make fe_test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        paths:
        - "src/main/scala/wacc/ASTNode.scala"
        - "src/main/scala/wacc/SemanticChecker.scala"
        - "src/main/scala/wacc/SymbolTable.scala"
        - "src/main/scala/wacc/TypeIdentifier.scala"
        - "src/main/scala/wacc/Error.scala"

back_end_test:
  stage: test
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make be_test