image: openjdk:8

build:
  stage: build
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make

test:
  stage: test
  script:
    - for i in src/test/*.wacc; do ./compile src/test/$i.wacc; done
