image: openjdk:8

build:
  stage: build
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make

front_end_test:
  stage: test
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make fe_test

back_end_test:
  stage: test
  script:
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - make be_test